name: jaansay_public_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  polygon_clipper: ^1.0.2
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.0.0
  intl: ^0.17.0
  material_design_icons_flutter: ^4.0.5955
  carousel_pro: ^1.0.0
  url_launcher: ^6.0.6
  flutter_linkify: ^5.0.2
  get_storage: ^2.0.2
  flutter_spinkit: ^5.0.0
  photo_view: ^0.11.1
  permission_handler: ^8.0.1
  flutter_downloader: ^1.6.1
  native_pdf_view: ^4.0.1
  persistent_bottom_nav_bar: ^4.0.2
  get: ^4.1.4
  pin_code_fields: ^7.2.0
  gender_picker: ^1.1.0
  google_maps_flutter: ^2.0.6
  video_player: ^2.1.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_dynamic_links: ^2.0.4
  firebase_messaging: ^10.0.0
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  dio: ^4.0.0
  file_picker: ^3.0.1
  share: ^2.0.4
  easy_localization: ^3.0.0
  pull_to_refresh: ^1.6.2
  steps: ^1.0.1
  provider: ^5.0.0
  geolocator: ^7.0.3
  package_info: ^2.0.2
  bubble: ^1.2.1
  chewie: ^1.2.0
  flutter_image_compress: ^1.0.0
  qr_flutter: ^4.0.0
  import_sorter: ^4.6.0
  get_it: ^6.0.0
  badges: ^1.2.0
  lottie: ^1.0.1
  google_fonts: ^2.0.0
  shimmer: ^2.0.0
  font_awesome_flutter: ^9.0.0
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.1.7+1

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/fonts/
   - assets/translations/
   - assets/anims/
   - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
